### ISSUE TITLE
Invalid integer setting

### ISSUE THREAD

**Issue by ghost** [Distributed-DeadLock/thelowerroad#1]
Cloned the latest Git version and installed the mod in Minetest 0.4.16. The road generates, but hose error messages appear in the shell.

~~~~
"017-12-02 23:12:48: ERROR[Main]: Invalid integer setting in /home/dirk/.minetest/mods/thelowerroad//settingtypes.txt "thelowerroad.sinfactor (The road wobble) int 62 40 10000
"017-12-02 23:12:48: ERROR[Main]: Invalid integer setting in /home/dirk/.minetest/mods/thelowerroad//settingtypes.txt "thelowerroad.sinspread (The spread of the road wobble) int 30 2 40
"017-12-02 23:12:48: ERROR[Main]: Invalid integer setting in /home/dirk/.minetest/mods/thelowerroad//settingtypes.txt "thelowerroad.house_rareness (Roadside-house rareness) int 0 0 11
~~~~

(With `"` at the beginning of the line. Maybe an accidental control character? See the double slash in the `settingtypes.txt` path.)

Also: I ran the road town to -19850 and only there was one single little chamber with a chest containing some random default items. ot sure if it’s directly related to the error messages.

~~~~
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
~~~~

~~~~
$ minetest --version
Minetest 0.4.16 (Linux)
Using Irrlicht 1.8.4
Build info: VER=0.4.16 BUILD_TYPE=Release RUN_IN_PLACE=0 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="/usr/share/minetest"
~~~~

**Comment by Distributed-DeadLock** [comment]
Sorry, for not replying earlier.

Unfortunately, i can't reproduce the error on my windows system.
So i'm wildly guessing that it's caused by some windows-linux differences.
Therefore i removed all carriage-return characters (and also one stray space character) from settingstypes.txt .

Please redownload and try again.

The roadside-house rareness issue is probably related to that, as the default setting was still set to create just underground rooms. Without a working settingstypes.txt, that couldn't be changed.
I updated the init.lua to have rareness set to 0 instead of 5, when then settings are not manually changed.
But even now, expect no more than one house per mapchunk.
The commonness of the roadside-houses depends on the hilliness of the map.
There is maximum one house per mapchunk. It is placed 3 nodes before the border of the mapchunk (with the higher z-value), if the road is locally straight at that position. 

Please report back, if the changes have solved that issue.

**Comment by ghost** [comment]
Looks fixed. :+1:

The messages do not appear and houses are generated more often (still very rare, but that’s on purpose according to your comment).

**Comment by Distributed-DeadLock** [comment]
Thank you.
From now on, i'll use the UNIX Text-File format.
