### ISSUE TITLE
Replace temperature zones with proper biome detection

### ISSUE THREAD

**Issue by tacotexmex** [Distributed-DeadLock/thelowerroad#3]
Now with proper biome detection in engine, the road style can be made to match the current biome. It’s called `minetest.get_biome_data`. Support for this would be neat.

Thanks for a great mod!

**Comment by Distributed-DeadLock** [comment]
sorry for not responding earlier, but i'm kind of occupied otherwise right now.

so, that is generally a good idea. 

but it exceeds the scope of this mod:
there is only one more brick-block type in the base-game, 
and the road-types are made through changing the brick-type.
so even with biome-detection, i could only produce one more road-type.

i would need to craft additional block-types and/or create an interface to register block-types for a specific biome. and this is out of the scope of this mod.

the idea is more suitable for a bigger mod that would manage all the "patterns of civilisation".

So, good idea but still not happening, i'm closing this issue.
